### ISSUE TITLE
@SquadronService(web: false) still builds web files

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron_builder#1]
Hi,

Thank you so much for your hard work! This is an amazing package! 🚀

Recently, I wanted to generate files for my `WorkerService` and annotated it with

```dart
@SquadronService(web: false)
```

in order to avoid generating web-related files, however, they still got generated.

**Comment by d-markey** [comment]
Hello,

thanks for your feedback :) but I can't reproduce the issue. I've published a new version, could you upgrade and try again?

**Comment by d-markey** [comment]
There's a breaking change BTW, your service should not implement the `operations` map anymore. It is now handled via a mixin, e.g.:

```dart
@SquadronService(web: false)
class MyService extends WorkerService with $MyServiceOperations
```

**Comment by techouse** [comment]
I see. I was using `squadron_builder: ^0.7.1` where it didn't work, but in `0.9.0` it works.

Have you maybe forgotten to publish `0.8.x` where it did work?

**Comment by d-markey** [comment]
I tend to version releases prior to 1.0 with a number that kind of reflects the usability of the package... so there are gaps in version numbers. Versions <= 0.7.1 could only handle base types, now version 0.9 can also handle serializable types (those that implement toJson() / fromJson()). It's crucial for Web platforms where only base types can cross worker boundaries.

So that was intended in fact!

I want to also add support for List<T> where T is serializable (and possibly Map<String, T>...). When this is implemented, 99% use-cases should be covered so I will release version 1.0. Then I will probably add more options, eg. to disable serialization in native-only scenarios where types are less of an issue.
